version: 1.0.{build}

image: ubuntu

install:
  #
  # Download Salesforce CLI and define environment variables
  #
  #Assign variables
  - export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  - export SFDX_AUTOUPDATE_DISABLE=false
  - export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
  - export SFDX_DOMAIN_RETRY=300
  - export SFDX_DISABLE_APP_HUB=true
  - export SFDX_LOG_LEVEL=DEBUG
  - export ROOTDIR=force-app/main/default/
  - export TESTLEVEL=RunLocalTests
  #Be sure to update the package ID (package Id will start with 0Ho) or package alias here from the sfdx-project.json file
  #- export PACKAGENAME="0Ho0N000000CaTISA0"
  #- export PACKAGEVERSION=""

  #Create sfdx directory
  - mkdir sfdx

  #Install Salesforce CLI
  - sudo wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
  - "./sfdx/install"
  - export PATH=./sfdx/$(pwd):$PATH
  - sfdx --version
  - sfdx plugins --core

  #Install JSON processeor
  - sudo apt-get install -y jq

build_script:
  #Decrypt server key
  - openssl enc -nosalt -aes-256-cbc -d -in SampleSalesforce/cert_asset/server.key.enc -out SampleSalesforce/cert_asset/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
  #Authorize Dev Hub
  - sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile SampleSalesforce/cert_asset/server.key --username $HUB_USER_NAME --setdefaultdevhubusername --setalias HubOrg
  #Create scratch org
  - sfdx force:org:create --targetdevhubusername HubOrg --setdefaultusername --definitionfile SampleSalesforce/config/project-scratch-def.json --setalias ciorg --wait 10 --durationdays 1
  - sfdx force:org:display --targetusername ciorg
  #Push source to scratch org
  - sfdx force:source:push --targetusername ciorg
  #Run unit tests on scratch org
  - sfdx force:apex:test:run --targetusername ciorg --wait 10 --resultformat tap --codecoverage --testlevel $TESTLEVEL
  #Delete scratch org
  - sfdx force:org:delete --targetusername ciorg --noprompt

test_script:
   #Decrypt server key
  - openssl enc -nosalt -aes-256-cbc -d -in SampleSalesforce/cert_asset/server.key.enc -out SampleSalesforce/cert_asset/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
  #Authorize Dev Hub
  - sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile SampleSalesforce/cert_asset/server.key --username $HUB_USER_NAME --setdefaultdevhubusername --setalias HubOrg
  #Create scratch org
  - sfdx force:org:create --targetdevhubusername HubOrg --setdefaultusername --definitionfile SampleSalesforce/config/project-scratch-def.json --setalias ciorg --wait 10 --durationdays 1
  - sfdx force:org:display --targetusername ciorg
   #Delete scratch org
  - sfdx force:org:delete --targetusername ciorg --noprompt

  
  
 